#!/bin/bash
# Quick reference commands for standalone repository

echo "================================================"
echo "PostgreSQL Outline Plugin - Standalone Repository"
echo "Quick Reference Commands"
echo "================================================"
echo ""

echo "📁 Repository Information:"
echo "  Total files: $(find . -type f | wc -l)"
echo "  C source files: $(find src -name '*.c' 2>/dev/null | wc -l)"
echo "  Header files: $(find include -name '*.h' 2>/dev/null | wc -l)"
echo "  Test files: $(find test -name '*.sql' 2>/dev/null | wc -l)"
echo "  Documentation: $(find . -name '*.md' | wc -l) files"
echo ""

echo "🚀 Quick Start Commands:"
echo ""
echo "1️⃣  Setup Repository:"
echo "   bash setup-standalone.sh"
echo ""
echo "2️⃣  Build Plugin:"
echo "   make PG_CONFIG=/usr/lib/postgresql/12/bin/pg_config"
echo ""
echo "3️⃣  Validate:"
echo "   bash validate.sh"
echo ""
echo "4️⃣  Install:"
echo "   sudo make install PG_CONFIG=/usr/lib/postgresql/12/bin/pg_config"
echo ""
echo "5️⃣  Test with Docker:"
echo "   docker-compose up -d"
echo "   docker-compose exec postgres psql -U postgres -d testdb"
echo ""

echo "📤 GitHub Deployment:"
echo ""
echo "1. Create repository on GitHub"
echo "2. git remote add origin https://github.com/YOUR_USERNAME/pg-outline-plugin.git"
echo "3. git push -u origin main"
echo "4. git push origin v1.0.0"
echo ""

echo "📚 Documentation Files:"
echo "  📖 REPOSITORY_READY_CN.md  - 中文完整指南"
echo "  📖 STANDALONE_SETUP.md     - English setup guide"
echo "  📖 README.md               - User documentation"
echo "  📖 CONTRIBUTING.md         - Contribution guide"
echo "  📖 CHANGELOG.md            - Version history"
echo "  📖 SECURITY.md             - Security policy"
echo ""

echo "🐳 Docker Commands:"
echo "  Build:  docker build -t pg_outline:latest ."
echo "  Start:  docker-compose up -d"
echo "  Logs:   docker-compose logs -f"
echo "  Test:   docker-compose exec postgres psql -U postgres"
echo "  Stop:   docker-compose down"
echo ""

echo "✅ Status: Repository ready for deployment!"
echo "================================================"
